<?php

use App\Models\Category;
use App\Models\CategoryDescription;
use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $list = [
            [ 'name' => 'Automotive', 'sort_order'=>1, 'parent_id'=>null],
            [ 'name' => 'Baby & Toddler', 'sort_order'=>2, 'parent_id'=>null],
            [ 'name' => 'Clothing & Shoes', 'sort_order'=>3, 'parent_id'=>null],
            [ 'name' => 'Computers', 'sort_order'=>4, 'parent_id'=>null],
            [ 'name' => 'Electronics', 'sort_order'=>5, 'parent_id'=>null],
            [ 'name' => 'Entertainment & Arts', 'sort_order'=>6, 'parent_id'=>null],
            [ 'name' => 'Food & Gifts', 'sort_order'=>7, 'parent_id'=>null],
            [ 'name' => 'Health & Beauty', 'sort_order'=>8, 'parent_id'=>null],
            [ 'name' => 'Home & Garden', 'sort_order'=>9, 'parent_id'=>null],
            [ 'name' => 'Office & Professional Services', 'sort_order'=>10, 'parent_id'=>null],
            [ 'name' => 'Personal & Home Services', 'sort_order'=>11, 'parent_id'=>null],
            [ 'name' => 'Restaurants & Dining', 'sort_order'=>12, 'parent_id'=>null],
            [ 'name' => 'Software', 'sort_order'=>13, 'parent_id'=>null],
            [ 'name' => 'Sports & Outdoors', 'sort_order'=>14, 'parent_id'=>null],
            [ 'name' => 'Travel', 'sort_order'=>15, 'parent_id'=>null],

            [ 'name' => 'Auto Parts', 'sort_order'=>1, 'parent_id'=>1],
            [ 'name' => 'Tires', 'sort_order'=>1, 'parent_id'=>1],
            [ 'name' => 'Companies with Auto Services', 'sort_order'=>1, 'parent_id'=>1],
            [ 'name' => 'Motorcycle & ATV Parts and Gear', 'sort_order'=>1, 'parent_id'=>1],
            [ 'name' => 'Baby Furniture', 'sort_order'=>1, 'parent_id'=>2],
            [ 'name' => 'Baby Gear', 'sort_order'=>1, 'parent_id'=>2],
            [ 'name' => 'Baby Care & Safety', 'sort_order'=>1, 'parent_id'=>2],
            [ 'name' => 'Baby Clothing', 'sort_order'=>1, 'parent_id'=>3],
            [ 'name' => 'Shoes', 'sort_order'=>1, 'parent_id'=>3],
            [ 'name' => 'Jewelry', 'sort_order'=>1, 'parent_id'=>3],
            [ 'name' => 'Watches', 'sort_order'=>1, 'parent_id'=>3],
            [ 'name' => 'Clothing Accessories', 'sort_order'=>1, 'parent_id'=>3],
            [ 'name' => 'Costumes', 'sort_order'=>1, 'parent_id'=>3],
            [ 'name' => 'Kids\' Clothing', 'sort_order'=>1, 'parent_id'=>3],
            [ 'name' => 'Women\'s Clothing', 'sort_order'=>1, 'parent_id'=>3],
            [ 'name' => 'Men\'s Clothing', 'sort_order'=>1, 'parent_id'=>3],
            [ 'name' => 'Handbags', 'sort_order'=>1, 'parent_id'=>3],
            [ 'name' => 'Uniforms & Scrubs', 'sort_order'=>1, 'parent_id'=>3],
            [ 'name' => 'Teen Clothing', 'sort_order'=>1, 'parent_id'=>3],
            [ 'name' => 'Laptops', 'sort_order'=>1, 'parent_id'=>4],
            [ 'name' => 'Desktop Computers', 'sort_order'=>1, 'parent_id'=>4],
            [ 'name' => 'Computer Monitors', 'sort_order'=>1, 'parent_id'=>4],
            [ 'name' => 'Laptop Bags', 'sort_order'=>1, 'parent_id'=>4],
            [ 'name' => 'Hardware & Peripherals', 'sort_order'=>1, 'parent_id'=>4],
            [ 'name' => 'Computer Networking', 'sort_order'=>1, 'parent_id'=>4],
            [ 'name' => 'Printers & Office Electronics', 'sort_order'=>1, 'parent_id'=>4],
            [ 'name' => 'Tablets', 'sort_order'=>1, 'parent_id'=>4],
            [ 'name' => 'Video Games & Consoles', 'sort_order'=>1, 'parent_id'=>5],
            [ 'name' => 'Cameras & Camcorders', 'sort_order'=>1, 'parent_id'=>5],
            [ 'name' => 'Televisions', 'sort_order'=>1, 'parent_id'=>5],
            [ 'name' => 'MP3 & Media Players', 'sort_order'=>1, 'parent_id'=>5],
            [ 'name' => 'Home Theater', 'sort_order'=>1, 'parent_id'=>5],
            [ 'name' => 'Car Electronics', 'sort_order'=>1, 'parent_id'=>5],
            [ 'name' => 'Electronics Accessories', 'sort_order'=>1, 'parent_id'=>5],
            [ 'name' => 'Gadgets', 'sort_order'=>1, 'parent_id'=>5],
            [ 'name' => 'Cell Phone Accessories', 'sort_order'=>1, 'parent_id'=>5],
            [ 'name' => 'Companies with Cell Phones & Plans', 'sort_order'=>1, 'parent_id'=>5],
            [ 'name' => 'Headphones', 'sort_order'=>1, 'parent_id'=>5],
            [ 'name' => 'Smartwatches', 'sort_order'=>1, 'parent_id'=>5],
            [ 'name' => 'Companies with Tickets', 'sort_order'=>1, 'parent_id'=>6],
            [ 'name' => 'Media', 'sort_order'=>1, 'parent_id'=>6],
            [ 'name' => 'Collectibles', 'sort_order'=>1, 'parent_id'=>6],
            [ 'name' => 'Toys & Games', 'sort_order'=>1, 'parent_id'=>6],
            [ 'name' => 'Crafts & Fabrics', 'sort_order'=>1, 'parent_id'=>6],
            [ 'name' => 'Companies with Discount Clubs', 'sort_order'=>1, 'parent_id'=>6],
            [ 'name' => 'Musical Instruments', 'sort_order'=>1, 'parent_id'=>6],
            [ 'name' => 'Party & Event Supplies', 'sort_order'=>1, 'parent_id'=>6],
            [ 'name' => 'Sheet Music', 'sort_order'=>1, 'parent_id'=>6],
            [ 'name' => 'Specialty Food', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Flower Delivery', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Personalized Gifts', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Stationery & Cards', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Companies with Gift Clubs', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Photo Gifts & Prints', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Gift Cards', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Gift Baskets', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Groceries', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Food Storage', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Religious', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Beverages', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Special Diet', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Meat & Seafood', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Cheese', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Desserts & Sweets', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Packaged Meals & Snacks', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Popcorn', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Convenience Stores', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Novelty Gifts', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Cigars', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Fruit Gifts', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Vaping', 'sort_order'=>1, 'parent_id'=>7],
            [ 'name' => 'Personal Care', 'sort_order'=>1, 'parent_id'=>8],
            [ 'name' => 'Cosmetics', 'sort_order'=>1, 'parent_id'=>8],
            [ 'name' => 'Supplements', 'sort_order'=>1, 'parent_id'=>8],
            [ 'name' => 'Hair Care', 'sort_order'=>1, 'parent_id'=>8],
            [ 'name' => 'Fragrances', 'sort_order'=>1, 'parent_id'=>8],
            [ 'name' => 'Skin Care', 'sort_order'=>1, 'parent_id'=>8],
            [ 'name' => 'Dental Care', 'sort_order'=>1, 'parent_id'=>8],
            [ 'name' => 'Independent Living', 'sort_order'=>1, 'parent_id'=>8],
            [ 'name' => 'Medical Supplies', 'sort_order'=>1, 'parent_id'=>8],
            [ 'name' => 'Men\'s Grooming', 'sort_order'=>1, 'parent_id'=>8],
            [ 'name' => 'Sexual Wellness', 'sort_order'=>1, 'parent_id'=>8],
            [ 'name' => 'Vision Care', 'sort_order'=>1, 'parent_id'=>8],
            [ 'name' => 'Pet Supplies & Products', 'sort_order'=>1, 'parent_id'=>9],
            [ 'name' => 'Luggage', 'sort_order'=>1, 'parent_id'=>9],
            [ 'name' => 'Furniture', 'sort_order'=>1, 'parent_id'=>9],
            [ 'name' => 'Appliances', 'sort_order'=>1, 'parent_id'=>9],
            [ 'name' => 'Bed & Bath', 'sort_order'=>1, 'parent_id'=>9],
            [ 'name' => 'Home Decor', 'sort_order'=>1, 'parent_id'=>9],
            [ 'name' => 'Tools & Accessories', 'sort_order'=>1, 'parent_id'=>9],
            [ 'name' => 'Storage & Organization', 'sort_order'=>1, 'parent_id'=>9],
            [ 'name' => 'Vacuums & Cleaning Products', 'sort_order'=>1, 'parent_id'=>9],
            [ 'name' => 'Cookware & Cutlery', 'sort_order'=>1, 'parent_id'=>9],
            [ 'name' => 'Tableware', 'sort_order'=>1, 'parent_id'=>9],
            [ 'name' => 'Small Appliances', 'sort_order'=>1, 'parent_id'=>9],
            [ 'name' => 'Plants & Gardening', 'sort_order'=>1, 'parent_id'=>9],
            [ 'name' => 'Pools & Supplies', 'sort_order'=>1, 'parent_id'=>9],
            [ 'name' => 'Blinds', 'sort_order'=>1, 'parent_id'=>9],
            [ 'name' => 'Home Improvement', 'sort_order'=>1, 'parent_id'=>9],
            [ 'name' => 'Companies with Career Services', 'sort_order'=>1, 'parent_id'=>10],
            [ 'name' => 'Office Supplies', 'sort_order'=>1, 'parent_id'=>10],
            [ 'name' => 'Office Furniture', 'sort_order'=>1, 'parent_id'=>10],
            [ 'name' => 'Companies with Payroll', 'sort_order'=>1, 'parent_id'=>10],
            [ 'name' => 'Ink & Toner', 'sort_order'=>1, 'parent_id'=>10],
            [ 'name' => 'Companies with Online Meetings & Communication', 'sort_order'=>1, 'parent_id'=>10],
            [ 'name' => 'Business Cards & Printing', 'sort_order'=>1, 'parent_id'=>10],
            [ 'name' => 'School Supplies', 'sort_order'=>1, 'parent_id'=>10],
            [ 'name' => 'Companies with Marketing & PR', 'sort_order'=>1, 'parent_id'=>10],
            [ 'name' => 'Companies with Small Business Legal Services', 'sort_order'=>1, 'parent_id'=>10],
            [ 'name' => 'Companies with Web Hosting & Tools', 'sort_order'=>1, 'parent_id'=>10],
            [ 'name' => 'Bookkeeping', 'sort_order'=>1, 'parent_id'=>10],
            [ 'name' => 'Checks', 'sort_order'=>1, 'parent_id'=>10],
            [ 'name' => 'Restaurant Supplies', 'sort_order'=>1, 'parent_id'=>10],
            [ 'name' => 'Stock Images & Videos', 'sort_order'=>1, 'parent_id'=>10],
            [ 'name' => 'Companies with Professional Development', 'sort_order'=>1, 'parent_id'=>10],
            [ 'name' => 'Custom Printing', 'sort_order'=>1, 'parent_id'=>10],
            [ 'name' => 'Companies with Financial Services', 'sort_order'=>1, 'parent_id'=>11],
            [ 'name' => 'Companies with Dating', 'sort_order'=>1, 'parent_id'=>11],
            [ 'name' => 'Companies with Personal Legal Services', 'sort_order'=>1, 'parent_id'=>11],
            [ 'name' => 'Companies with Genealogy', 'sort_order'=>1, 'parent_id'=>11],
            [ 'name' => 'Companies with Tutoring & Test Prep', 'sort_order'=>1, 'parent_id'=>11],
            [ 'name' => 'Companies with Sitters & Nannies', 'sort_order'=>1, 'parent_id'=>11],
            [ 'name' => 'Companies with People Search', 'sort_order'=>1, 'parent_id'=>11],
            [ 'name' => 'Companies with Home Services', 'sort_order'=>1, 'parent_id'=>11],
            [ 'name' => 'Companies with Online Weight Loss Plans', 'sort_order'=>1, 'parent_id'=>11],
            [ 'name' => 'Companies with Meal Delivery', 'sort_order'=>1, 'parent_id'=>11],
            [ 'name' => 'Fast Food', 'sort_order'=>1, 'parent_id'=>12],
            [ 'name' => 'Casual Dining', 'sort_order'=>1, 'parent_id'=>12],
            [ 'name' => 'Italian', 'sort_order'=>1, 'parent_id'=>12],
            [ 'name' => 'Steak', 'sort_order'=>1, 'parent_id'=>12],
            [ 'name' => 'Seafood', 'sort_order'=>1, 'parent_id'=>12],
            [ 'name' => 'Breakfast', 'sort_order'=>1, 'parent_id'=>12],
            [ 'name' => 'Mexican', 'sort_order'=>1, 'parent_id'=>12],
            [ 'name' => 'Bar & Grill', 'sort_order'=>1, 'parent_id'=>12],
            [ 'name' => 'Companies with Restaurant Delivery', 'sort_order'=>1, 'parent_id'=>12],
            [ 'name' => 'Tax Preparation', 'sort_order'=>1, 'parent_id'=>13],
            [ 'name' => 'Companies with Online Backup', 'sort_order'=>1, 'parent_id'=>13],
            [ 'name' => 'Maintenance & Utilities', 'sort_order'=>1, 'parent_id'=>13],
            [ 'name' => 'Web Design & Development', 'sort_order'=>1, 'parent_id'=>13],
            [ 'name' => 'Graphics & Photo Editing', 'sort_order'=>1, 'parent_id'=>13],
            [ 'name' => 'Audio & Video Editing', 'sort_order'=>1, 'parent_id'=>13],
            [ 'name' => 'Personal Finance', 'sort_order'=>1, 'parent_id'=>13],
            [ 'name' => 'Productivity', 'sort_order'=>1, 'parent_id'=>13],
            [ 'name' => 'Antivirus & Security', 'sort_order'=>1, 'parent_id'=>13],
            [ 'name' => 'Education', 'sort_order'=>1, 'parent_id'=>13],
            [ 'name' => 'Outdoor Recreation', 'sort_order'=>1, 'parent_id'=>14],
            [ 'name' => 'Sportswear & Gear', 'sort_order'=>1, 'parent_id'=>14],
            [ 'name' => 'Indoor Games & Recreation', 'sort_order'=>1, 'parent_id'=>14],
            [ 'name' => 'Team Apparel & Merchandise', 'sort_order'=>1, 'parent_id'=>14],
            [ 'name' => 'Golf', 'sort_order'=>1, 'parent_id'=>14],
            [ 'name' => 'Team Sports Equipment', 'sort_order'=>1, 'parent_id'=>14],
            [ 'name' => 'Water Sports', 'sort_order'=>1, 'parent_id'=>14],
            [ 'name' => 'Winter Sports', 'sort_order'=>1, 'parent_id'=>14],
            [ 'name' => 'Fitness', 'sort_order'=>1, 'parent_id'=>14],
            [ 'name' => 'Billiards', 'sort_order'=>1, 'parent_id'=>14],
            [ 'name' => 'Companies with Flights', 'sort_order'=>1, 'parent_id'=>15],
            [ 'name' => 'Companies with Hotels', 'sort_order'=>1, 'parent_id'=>15],
            [ 'name' => 'Companies with Car Rental', 'sort_order'=>1, 'parent_id'=>15],
            [ 'name' => 'Companies with Cruises', 'sort_order'=>1, 'parent_id'=>15],
            [ 'name' => 'Companies with Vacation Packages', 'sort_order'=>1, 'parent_id'=>15],
            [ 'name' => 'Companies with Resorts', 'sort_order'=>1, 'parent_id'=>15],
            [ 'name' => 'Companies with Rail & Car Services', 'sort_order'=>1, 'parent_id'=>15],
            [ 'name' => 'Companies with Travel Services', 'sort_order'=>1, 'parent_id'=>15],
            [ 'name' => 'Companies with Vacation Homes', 'sort_order'=>1, 'parent_id'=>15]
        ];

        foreach ($list as $item) {
            $model = new Category();
            $model->name = $item['name'];
            $model->sort_order = $item['sort_order'];
            $model->image = '';
            $model->parent_id = $item['parent_id'];
            $model->save();


        }

    }
}
